fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      # Run the Ruff formatter.
      - id: ruff-format
        args: [--config=pyproject.toml]
      # Run the Ruff linter.
      - id: ruff
        args: [--exit-non-zero-on-fix, --fix, --config=pyproject.toml]
        files: ^(docling_mcp|tests)/.*\.py$
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: uv run --no-sync mypy docling_mcp tests
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: pytest
        name: Pytest
        language: system
        entry: uv run --no-sync pytest --cov=docling_mcp --cov-report=xml tests
        pass_filenames: false
        files: '\.py$'
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.16
    hooks:
      - id: uv-lock
