exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",

]

line-length = 100
indent-width = 4
target-version = "py311"

# enable fix by default
fix = true

[format]
docstring-code-format = true

[lint]
select = ["E4", "E7", "E9", "F", "I"]
ignore = ["D202", "E501", "E741"]

fixable = ["ALL"]
unfixable = []

[lint.pydocstyle]
convention = "google"
